[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ranked_choice_assigner"
version = "0.0.11"
authors = [{ name = "Rafay Khan" }]
maintainers = [{ name = "Rafay Khan" }]
description = "An algorithm/automation program for assigning people to (simultaneous) events based on ranked preferences."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyyaml",
]

[project.optional-dependencies]
development = [
    "black", 
    "ruff", 
    "pytype",
]

[tool.ruff]
line-length = 88
select = [
    "E",  # pycodestyle
    "F",  # pyflakes
    "UP", # pyupgrade
    "D",  # pydocstyle
    "I", # isort
]

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]